# Generated by Django 6.0.4 on 2026-05-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('transaction_type', models.CharField(choices=[('vente', 'À vendre'), ('location', 'À louer')], default='vente', max_length=20, verbose_name='Type de transaction')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendu', 'Vendu'), ('loue', 'Loué'), ('reserve', 'Réservé')], default='disponible', max_length=20, verbose_name='Statut')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Devise')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface')),
                ('area_unit', models.CharField(default='m²', max_length=20, verbose_name='Unité surface')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chambres')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Toilettes / salles de bain')),
                ('floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Niveaux')),
                ('short_description', models.TextField(verbose_name='Description courte')),
                ('full_description', models.TextField(blank=True, verbose_name='Description complète')),
                ('has_water', models.BooleanField(default=False, verbose_name='Eau disponible')),
                ('has_electricity', models.BooleanField(default=False, verbose_name='Électricité disponible')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Jardin')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscine')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Légende')),
                ('is_main', models.BooleanField(default=False, verbose_name='Image principale')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Bien immobilier')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
